#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : x264
Version  : master
Release  : 2
URL      : https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
Source0  : https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: x264-bin = %{version}-%{release}
Requires: x264-lib = %{version}-%{release}
Requires: x264-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : nasm
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the x264 package.
Group: Binaries
Requires: x264-license = %{version}-%{release}

%description bin
bin components for the x264 package.


%package dev
Summary: dev components for the x264 package.
Group: Development
Requires: x264-lib = %{version}-%{release}
Requires: x264-bin = %{version}-%{release}
Provides: x264-devel = %{version}-%{release}
Requires: x264 = %{version}-%{release}

%description dev
dev components for the x264 package.


%package lib
Summary: lib components for the x264 package.
Group: Libraries
Requires: x264-license = %{version}-%{release}

%description lib
lib components for the x264 package.


%package license
Summary: license components for the x264 package.
Group: Default

%description license
license components for the x264 package.


%prep
%setup -q -n x264-master
cd %{_builddir}/x264-master

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693332795
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static --enable-shared
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1693332795
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/x264
cp %{_builddir}/x264-%{version}/COPYING %{buildroot}/usr/share/package-licenses/x264/dfac199a7539a404407098a2541b9482279f690d || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/x264

%files dev
%defattr(-,root,root,-)
/usr/include/x264.h
/usr/include/x264_config.h
/usr/lib64/libx264.so
/usr/lib64/pkgconfig/x264.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libx264.so.164

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/x264/dfac199a7539a404407098a2541b9482279f690d
